### ISSUE TITLE
support for other APIs

### ISSUE THREAD

**Issue by ifiaposto** [bespokelabsai/curator#179]
are there plans to support requests for other APIs != openai  e.g claude?

**Comment by RyanMarten** [comment]
Yes! @CharlieJCJ is adding this via #141 using litellm as a backend. We should then be able to support the following: https://docs.litellm.ai/docs/providers with basic prompting. 

For structured output, we are testing more individually and will provide a list of support models.

**Comment by CharlieJCJ** [comment]
@ifiaposto LiteLLM backend is tested and supported in `dev` branch now. We'll soon roll this out in official pypi packages. Thanks for the wait.

**Comment by RyanMarten** [comment]
@ifiaposto 

If you want to try this out now you can do 
```
pip install bespokelabs-curator@git+https://github.com/bespokelabsai/curator.git@dev
```
And run the [example for gemini](https://github.com/bespokelabsai/curator/blob/dev/examples/litellm_recipe_prompting.py)
```
python examples/litellm_recipe_prompting.py
```

Please let us know if you run into any issues!

**Comment by ifiaposto** [comment]
thanks so much, Ryan. great work!

yeap. it worked! I just needed to manually install dev branch: `pip install git+https://github.com/bespokelabsai/Curator.git@dev`

main is throwing:

`    TypeError: Prompter.__init__() got an unexpected keyword argument 'backend'                                                                                                                                  
`

after the right installation, I am getting some recipes :)) :

`024-12-04 12:56:12,663 - bespokelabs.curator.request_processor.base_online_request_processor - INFO - Status tracker: Tasks - Started: 10, In Progress: 0, Succeeded: 10, Failed: 0, Already Completed: 0
Errors - API: 0, Rate Limit: 0, Other: 0, Total: 0
                                              recipe     cuisine
0  ##  Spaghetti alla "Notte Stellata" (Starry Ni...     Italian
1  ## Spicy Sesame Lotus Root & Shrimp Stir-fry w...     Chinese
2  ##  Spicy Mango & Black Bean Tostadas with Chi...     Mexican
3  ##  Saumon en Croûte de Noix et Châtaignes, Sa...      French
4  ##  Negi-Mayo Miso Salmon with Crispy Sesame B...    Japanese
5  ## Spicy Mango & Chickpea Curry with Coconut &...      Indian
6  ##  Gaeng Som Pla Duk Yang Sai Ma-Kham (Spicy ...        Thai
7  ## Bún Gỏi Cuốn with Spicy Peanut-Tamarind Gla...  Vietnamese
8  ## Spicy Kimchi & Pork Belly Stir-fry with Swe...      Korean
9  ##  Moqueca de Banana com Camarão e Coco (Bana...   Brazilian
`

**Comment by RyanMarten** [comment]
Thanks! It was all @CharlieJCJ :D
