### ISSUE TITLE
Out of Space error on OpenAI servers

### ISSUE THREAD

**Issue by EtashGuha** [bespokelabsai/curator#189]
Error Type: TASK_EXECUTION_EXCEPTION

User exception:
ntime_resources/pip/14f34acc790047a95e39a14509b14c99a0377d40/virtualenv/lib/python3.10/site-packages/openai/_base_client.py", line 1634, in _request
 raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'You have exceeded your file storage quota. Organizations are limited to 100 GB of files. Please delete old files or attempt with a smaller file size.', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by RyanMarten** [comment]
Looking at the openai dashboard I'm seeing
batch uploads of 30MB. 
batch outputs of 14MB

The batch size is 10k, but these amounts will change based on the data strategy. 

Based on the most recent run
Thats ~2,200 batches to fill up 100GB

**Comment by RyanMarten** [comment]
As an immediate fix, I'll write a script that deletes all current files stored on the account - using the files.list API https://platform.openai.com/docs/api-reference/files/list

**Comment by RyanMarten** [comment]
Deleted all files - you can see no files are now listed in the dashboard 
https://platform.openai.com/storage
