### ISSUE TITLE
Gemini Flash runs very slow (1 it/s)

### ISSUE THREAD

**Issue by RyanMarten** [bespokelabsai/curator#223]
- api key and paid tier https://aistudio.google.com/app/apikey
- quota (rate limits) monitoring https://console.cloud.google.com/apis/api/generativelanguage.googleapis.com/quotas?inv=1&invt=AbjX7w&project=bespokelabs
- usage (server response and latency) montoring https://console.cloud.google.com/apis/api/generativelanguage.googleapis.com/metrics?project=bespokelabs

Only doing one request at a time

![Screenshot 2024-12-05 at 10 43 36 PM](https://github.com/user-attachments/assets/8ce89b86-9801-42c8-ab72-f66d4133c075)

**Comment by CharlieJCJ** [comment]
What happened here was that 1) we've set a slow default tpm, which is 150k, and 2) we did a conservative output token estimation, which doesn't exhaust the token capacity. 
Related issues: #206 

The fix for this is manually set the tpm to a higher value.

**Comment by CharlieJCJ** [comment]
Example script
```
from bespokelabs.curator import Prompter
from datasets import Dataset
import logging

logger = logging.getLogger("bespokelabs.curator")
logger.setLevel(logging.DEBUG)

dataset = Dataset.from_dict({"prompt": ["write me a poem"] * 100_000})

prompter = Prompter(
    prompt_func=lambda row: row["prompt"],
    model_name="gemini/gemini-1.5-flash-002",
    response_format=None,
    max_requests_per_minute=2000,
    max_tokens_per_minute=4000000,
)

dataset = prompter(dataset)
print(dataset.to_pandas())
```

**Comment by CharlieJCJ** [comment]
Also works for gemini-1.5-pro-002
